### PR TITLE
Use `missing` instead of `nothing` for dynamic values

### PR DESCRIPTION
**Pull request by Tokazama**

### CODE REVIEW

**Review by chriselrod — APPROVED** [review]

**Comment by Tokazama** [comment]
For some reason all tests are failing but at different places for different Julia versions. I'll have to do some more poking around.

**Comment by chriselrod** [comment]
> For some reason all tests are failing but at different places for different Julia versions. I'll have to do some more poking around.

This fixes some of them: https://github.com/JuliaArrays/ArrayInterface.jl/pull/230

**Comment by chriselrod** [comment]
Odd that this is getting an ambiguity error on `lu` for StaticArrays, when master isn't, and that code hasn't been touched in this PR?

**Comment by Tokazama** [comment]
I assumed that `missing` would have similar behavior as `nothing` since they're both singletons, but maybe there's some sort of compiler wizardry going on with `nothing` I'm not aware of.

**Comment by chriselrod** [comment]
The lu ambiguities are because it was using an old version of StaticArrays, before:
https://github.com/JuliaArrays/StaticArrays.jl/commit/7dc649948b26fc7e5c7525560d41064f221244a5

We could add a test/Project.toml to restrict the version it tests with.

**Comment by chriselrod** [comment]
Doc tests fail, but should pass once the pkg server updates and has Static 0.5 available.
So this should be good to go.

**Comment by Tokazama** [comment]
Since this is breaking, do we want to wait to register this until we manage other breaking changes like moving BandedMatrixIndex out

**Comment by chriselrod** [comment]
> Since this is breaking, do we want to wait to register this until we manage other breaking changes like moving BandedMatrixIndex out

Sure, no rush.

**Comment by Tokazama** [comment]
I just moved the banded matrix stuff into requires so that when we move to other packages nothing should change.

**Comment by YingboMa** [comment]
Is this breaking change really worth to make? The whole SciML ecosystem is still forced on v3 and not able to use new features.

**Comment by ChrisRackauckas** [comment]
It's been too long without downstream PRs. Let's revert it today.

**Comment by Tokazama** [comment]
Is the problem just with getting LoopVectorization updated or do we need to go through the whole ecosystem? I'd be surprised if many packages had to change anything to accommodate this.

**Pull request merged**
