### PR TITLE
views should preserve static axes information

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Review by Tokazama — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
This might've just caused some downstream failures? https://github.com/SciML/DiffEqSensitivity.jl/runs/6742066279?check_suite_focus=true#step:6:363

**Comment by Tokazama** [comment]
I think I figured it out and I'm working on a quick fix.

**Comment by chriselrod** [comment]
@Tokazama let me know if you've got this or want me to take a look.

**Comment by Tokazama** [comment]
I've got a quick fix in #297

**Pull request merged**
