### PR TITLE
Simplify implementation of known_length

### PR DESCRIPTION
**Pull request by Tokazama**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
It's static-free now?

**Comment by ChrisRackauckas** [comment]
Is this downstream failure related?

https://github.com/SciML/SciMLBase.jl/runs/6575690017?check_suite_focus=true#step:6:135

**Comment by Tokazama** [comment]
I don't think so, but I can look into it right now.

**Comment by ChrisRackauckas** [comment]
That turned out to be just bad versioning.

**Pull request merged**
