### PR TITLE
Implement is_lazy_wrapper

### PR DESCRIPTION
**Pull request by Tokazama**
Begin to address #253 and #136

### CODE REVIEW

**Comment by Tokazama** [comment]
@rafaqz Does the name `is_lazy_wrapper` work for you?

**Comment by rafaqz** [comment]
Whats lazy about it? `is_forwarding_wrapper` maybe?

**Comment by Tokazama** [comment]
@rafaqz , anything else?

**Comment by rafaqz** [comment]
You can remove the word "lazily" from the docs ;)

**Comment by Tokazama** [comment]
Good point

**Pull request merged**
