### PR TITLE
SnoopPrecompile common methods

### PR DESCRIPTION
**Pull request by chriselrod**
With ArrayInterface(Core) master:
```julia
julia> intersect(methodinstances(cf_odeq), methodinstances(cf_rf))
Set{Core.MethodInstance} with 17 elements:
  MethodInstance for Base.IteratorSize(::Type{Base.OneTo{Int64}})
  MethodInstance for ArrayInterfaceCore.known_step(::Type{Base.OneTo{Int64}})
  MethodInstance for ArrayInterfaceCore.is_forwarding_wrapper(::Type{Base.OneTo{Int64}})
  MethodInstance for ArrayInterfaceCore.known_first(::Type{Base.OneTo{Int64}})
  MethodInstance for ArrayInterface._maybe_known_length(::Base.HasShape{1}, ::Type{Base.O…
  MethodInstance for convert(::Type{Tuple{UnitRange{Int64}, UnitRange{Int64}}}, ::Tuple{U…
  MethodInstance for Base.indexed_iterate(::Tuple{Tuple{Int64}, typeof(identity)}, ::Int6…
  MethodInstance for Base._xfadjoint_unwrap(::Tuple{Int64})
  MethodInstance for ArrayInterface.known_length(::Type{Base.OneTo{Int64}})
  MethodInstance for ArrayInterfaceCore.known_last(::Type{Base.OneTo{Int64}})
  MethodInstance for Base.Generator{Tuple{Int64}, typeof(identity)}(::typeof(identity), :…
  MethodInstance for ArrayInterface._prod_or_nothing(::Tuple{Nothing})
  MethodInstance for ArrayInterface.known_size(::Type{Base.OneTo{Int64}})
  MethodInstance for getproperty(::Base.Generator{Tuple{Int64}, typeof(identity)}, ::Symb…
  MethodInstance for Base.Generator(::typeof(identity), ::Tuple{Int64})
  MethodInstance for Base.indexed_iterate(::Tuple{Tuple{Int64}, typeof(identity)}, ::Int6…
  MethodInstance for Base._xfadjoint_unwrap(::Base.Generator{Tuple{Int64}, typeof(identit…
```
With this PR:
```julia
julia> intersect(methodinstances(cf_odeq), methodinstances(cf_rf))
Set{Core.MethodInstance} with 8 elements:
  MethodInstance for Base.indexed_iterate(::Tuple{Tuple{Int64}, typeof(identity)}, ::Int6…
  MethodInstance for Base.Generator(::typeof(identity), ::Tuple{Int64})
  MethodInstance for convert(::Type{Tuple{UnitRange{Int64}, UnitRange{Int64}}}, ::Tuple{U…
  MethodInstance for Base.indexed_iterate(::Tuple{Tuple{Int64}, typeof(identity)}, ::Int6…
  MethodInstance for Base._xfadjoint_unwrap(::Tuple{Int64})
  MethodInstance for Base._xfadjoint_unwrap(::Base.Generator{Tuple{Int64}, typeof(identit…
  MethodInstance for getproperty(::Base.Generator{Tuple{Int64}, typeof(identity)}, ::Symb…
  MethodInstance for Base.Generator{Tuple{Int64}, typeof(identity)}(::typeof(identity), :…
```

### CODE REVIEW

**Comment by timholy** [comment]
Nice! Any measurable benefit for load times when you load both packages?

**Comment by chriselrod** [comment]
> Nice! Any measurable benefit for load times when you load both packages?

No measurable difference.
Master:
```julia
julia> @time using OrdinaryDiffEq
 17.700264 seconds (72.74 M allocations: 11.539 GiB, 6.41% gc time, 0.53% compilation time)

julia> using PkgCacheInspector

julia> cf_odeq = info_cachefile("OrdinaryDiffEq")
┌ Warning: Replacing module `OrdinaryDiffEq`
└ @ Base loading.jl:1610
Contents of /home/chriselrod/.julia/compiled/v1.10/OrdinaryDiffEq/DlSvy_scZsf.so:
  modules: Any[OrdinaryDiffEq]
  2870 external methods
  17673 new specializations of external methods (Base 52.6%, UnPack 15.2%, Base.Broadcast 14.5%, ...)
  845 external methods with new roots
  29090 external targets
  29749 edges
  file size:   145163320 (138.439 MiB)
  Segment sizes (bytes):
  system:      27658744 ( 23.80%)
  isbits:      85301355 ( 73.40%)
  symbols:       134563 (  0.12%)
  tags:          388409 (  0.33%)
  relocations:  2651694 (  2.28%)
  gvars:          22720 (  0.02%)
  fptrs:          62000 (  0.05%)
```
PR:
```julia
julia> @time using OrdinaryDiffEq
 17.607371 seconds (72.39 M allocations: 11.520 GiB, 6.29% gc time, 0.55% compilation time)

julia> using PkgCacheInspector

julia> cf_odeq = info_cachefile("OrdinaryDiffEq")
┌ Warning: Replacing module `OrdinaryDiffEq`
└ @ Base loading.jl:1610
Contents of /home/chriselrod/.julia/compiled/v1.10/OrdinaryDiffEq/DlSvy_gq1qu.so:
  modules: Any[OrdinaryDiffEq]
  2855 external methods
  17075 new specializations of external methods (Base 52.5%, UnPack 15.7%, Base.Broadcast 13.9%, ...)
  850 external methods with new roots
  28463 external targets
  29296 edges
  file size:   139104280 (132.660 MiB)
  Segment sizes (bytes):
  system:      27335192 ( 24.78%)
  isbits:      79792035 ( 72.32%)
  symbols:       135676 (  0.12%)
  tags:          383162 (  0.35%)
  relocations:  2597879 (  2.35%)
  gvars:          22712 (  0.02%)
  fptrs:          62000 (  0.06%)
```

But these methods are so cheap to compile, I wouldn't expect a benefit.

**Comment by timholy** [comment]
You probably also want to do this analysis on independent rather than dependent packages.

**Comment by ChrisRackauckas** [comment]
These will at least show up a lot.

**Comment by chriselrod** [comment]
> You probably also want to do this analysis on independent rather than dependent packages.

Yes, as I said on slack, I was expecting this intersection to be empty because the packages are dependent.

**Pull request merged**
