### PR TITLE
correct Requires usage to fix issues with PackageCompiler sysimages

### PR DESCRIPTION
**Pull request by KristofferC**
Basically, the rule for Requires to work with sysimages is that it should load no package non-relatively.

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]
Thanks!

**Comment by KristofferC** [comment]
So `Adapt` is not loaded in ArrayInterface which means the `using ..Adapt` for Requires doesn't work. I don't see a way to be relocatable for Requries with that setup. I put it back how things were for that specific extension though.

**Comment by ChrisRackauckas** [comment]
Adapt's stuff got upstreamed to Adapt.jl so that's fine.

**Comment by KristofferC** [comment]
But there is a function below using it?

**Comment by ChrisRackauckas** [comment]
🤦

**Pull request merged**
