### PR TITLE
Generalize from `Array` to `<:DenseArray` in `dense_dims`

### PR DESCRIPTION
**Pull request by brenhinkeller**
Follow-up to #243 (missed one!)

### CODE REVIEW

**Review by chriselrod — APPROVED** [review]

**Comment by brenhinkeller** [comment]
Hmm, think these downstream failures are related?
```
Static Zero and One: Test Failed at /home/runner/work/ArrayInterface.jl/ArrayInterface.jl/downstream/test/runtests.jl:1930
313
  Expression: f(vx, VectorizationBase.Zero()) === f(VectorizationBase.Zero(), vx) === VectorizationBase.Zero()
314
   Evaluated: Vec{8, Float64}<0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0> === Vec{8, Float64}<0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0> === static(0)
315
```
```
Static Zero and One: Test Failed at /home/runner/work/ArrayInterface.jl/ArrayInterface.jl/downstream/test/runtests.jl:1930
304
  Expression: f(vx, VectorizationBase.Zero()) === f(VectorizationBase.Zero(), vx) === VectorizationBase.Zero()
305
   Evaluated: Vec{8, Float64}<0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0> === Vec{8, Float64}<0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0> === static(0)
```

**Comment by Tokazama** [comment]
It's odd that it fails for VectorizationBase and not for LoopVectorization

**Comment by brenhinkeller** [comment]
Hmm, true

**Comment by chriselrod** [comment]
Those look more likely to be related to a change in Static.jl?

**Comment by brenhinkeller** [comment]
Ah, cool

**Comment by Tokazama** [comment]
> Those look more likely to be related to a change in Static.jl?

Recent changes to Static shouldn't change functionality. Is there anyway those results would be due to a change in inference?

**Comment by chriselrod** [comment]
> > Those look more likely to be related to a change in Static.jl?
> 
> Recent changes to Static shouldn't change functionality. Is there anyway those results would be due to a change in inference?

The failures were on Julia 1.7.2, not master, so it seems like we should have seen this before.

Minimal example:
```julia
julia> using VectorizationBase

julia> using Static: Zero

julia> vx = Vec(ntuple(_->randn(),pick_vector_width(Float64))...)
Vec{8, Float64}<-0.5504011052532674, -2.5682643037386494, 0.801916505984965, -0.11851130499131975, -0.6657311323634413, -0.21326198876441116, -0.5590752776040665, -0.9572457704964606>

julia> vx * Zero()
Vec{8, Float64}<-0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, -0.0>

julia> @which vx * Zero()
*(x::Real, y::StaticInt) in Static at /home/chriselrod/.julia/dev/Static/src/int.jl:62
```
Line 62 is a newly added line:
https://github.com/SciML/Static.jl/blob/16f441fb3239c09a580c57c028607274116efb43/src/int.jl#L62

**Comment by chriselrod** [comment]
With Static 0.6.2:
```julia
julia> using Static: Zero

julia> 3 * Zero()
static(0)
```
With Static 0.6.3, we get `0::Int` instead.

**Pull request merged**
