### PR TITLE
fix  `UndefVarError: @assume_effects not defined`

### PR DESCRIPTION
**Pull request by anandijain**
from recent update, i couldn't precompile this package

### CODE REVIEW

**Comment by BioTurboNick** [comment]
Was just about to report this, can't run my code in Pluto. Please push a revision ASAP.

**Comment by BioTurboNick** [comment]
Or pull the current one.

**Comment by Tokazama** [comment]
Thanks for catching this. I'll get a patch release out immediately.

**Comment by BioTurboNick** [comment]
Thanks @Tokazama . I was wondering why it passed CI, and I noticed this:

image

It appears to be downgrading the ArrayInterfaceCore version?

**Comment by Tokazama** [comment]
I'm not sure. There's still some funky stuff going on with the some of these checks. I think we got most of it fixed but there's obviously some stuff that isn't working yet.

**Pull request merged**
