### PR TITLE
Assume parent array has same strides

### PR DESCRIPTION
**Pull request by Tokazama**
Assume strides are same for parent unless explicitly defined now. I'm not completely sure we are dealing with `ReshapedArray` in the best way, but I'm also not sure there is an ideal approach.

### CODE REVIEW

**Comment by chriselrod** [comment]
Seems like `reinterpret` is hitting this for Julia 1.2.

**Comment by chriselrod** [comment]
None of my libraries support Julia versions older than 1.5, so I'm fine with making the `reinterpret` tests conditional only trigger for these newer Julia versions.

**Comment by Tokazama** [comment]
> None of my libraries support Julia versions older than 1.5, so I'm fine with making the reinterpret tests conditional only trigger for these newer Julia versions.

Is that going to be a sufficient solution or do you think it will break other packages? I'm assuming your stuff is the only thing directly using strides but I haven't done any formal downstream testing (nor do I know how to do that for over 700 packages that depend on this.

**Review by chriselrod — APPROVED** [review]
LGTM.

**Pull request merged**
